
export const K_SETTINGS='muni_settings_v1';export const K_SEQ='muni_seq_v1';export const K_PF_MONO='muni_pf_mono_v1';export const K_PF_RI='muni_pf_ri_v1';
export const $=(q,root=document)=>root.querySelector(q);
export function loadSettings(){return JSON.parse(localStorage.getItem(K_SETTINGS)||'{}')}export function saveSettings(s){localStorage.setItem(K_SETTINGS,JSON.stringify(s))}export function clearSettings(){localStorage.removeItem(K_SETTINGS)}
export function getSeq(){return JSON.parse(localStorage.getItem(K_SEQ)||'{}')}export function bumpSeq(tipo,curso){const seq=getSeq();const key=`${(curso||'GEN').toUpperCase()}-${tipo}`;seq[key]=(seq[key]||0)+1;localStorage.setItem(K_SEQ,JSON.stringify(seq));return seq[key]}
export function fmtRegistro(tipo){const s=loadSettings();const n=bumpSeq(tipo,s.curso);const num=String(n).padStart(4,'0');return `${s.prefijo||'ESCOBAR360'}-${s.year||new Date().getFullYear()}-${(s.curso||'GEN').replace(/\s+/g,'')}-${tipo}-${num}`.toUpperCase()}
export function validCUIT(c){if(!/^\d{11}$/.test(c||''))return false;const a=c.split('').map(Number),w=[5,4,3,2,7,6,5,4,3,2];let s=0;for(let i=0;i<10;i++)s+=a[i]*w[i];let d=11-(s%11);if(d===11)d=0;else if(d===10)d=9;return d===a[10]}export const validPhone=(p)=>/^\d{6,15}$/.test(p||'');export const validEmail=(e)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e||'');export const validCP=(cp)=>/^\d{4}$/.test(cp||'');
export const lsGet=(k)=>JSON.parse(localStorage.getItem(k)||'[]');export const lsSet=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
export class MiniQR{constructor(el){this.el=el}make(text){const c=document.createElement('canvas'),s=128;c.width=c.height=s;const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,s,s);g.fillStyle='#000';const f=(x,y)=>{g.fillRect(x,y,28,28);g.fillStyle='#fff';g.fillRect(x+6,y+6,16,16);g.fillStyle='#000';g.fillRect(x+10,y+10,8,8)};f(6,6);f(s-34,6);f(6,s-34);let h=0;for(const ch of String(text)){h=(h*31+ch.charCodeAt(0))>>>0}for(let y=0;y<40;y++){for(let x=0;x<40;x++){if(((x*1103515245+y*12345+h)>>5)&1){g.fillRect(36+x*2,36+y*2,2,2)}}}this.el.innerHTML='';this.el.appendChild(c)}}
